### ISSUE TITLE
请问如何在群辉docker中正常使用

### ISSUE THREAD

**Issue by LoCCai** [LLOneBot/llonebot-docker#9]
xorg-server 2:21.1.4-2ubuntu1.7~22.04.8 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.40.0
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.0.log", Time: Wed May  1 10:37:50 2024
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
xf86EnableIO: failed to enable I/O ports 0000-03ff (Operation not permitted)
vesa: Refusing to run on UEFI
xf86EnableIO: failed to enable I/O ports 0000-03ff (Operation not permitted)
vesa: Refusing to run on UEFI
(EE) 
Fatal server error:
(EE) no screens found(EE) 
(EE) 
Please consult the The X.Org Foundation support 
	 at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/var/log/Xorg.0.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/lib/python3/dist-packages/supervisor/options.py:473: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  self.warnings.warn(
xinit: giving up
xinit: unable to connect to X server: Cannot assign requested address
xinit: server error

报错似乎显示缺少屏幕？还有链接服务器失败什么的，不太懂，想问一下这个在我的云服务器可以正常使用，应该不需要屏幕吧？请问需要如何配置解决这个问题

**Comment by MliKiowa** [comment]
https://github.com/LLOneBot/llonebot-docker?tab=readme-ov-file#alternative
